### ISSUE TITLE
我的一点小建议

### ISSUE THREAD

**Issue by Web-Cooler** [cy745/LMusic#10]
以下是我的一点意见，希望作者可以酌情采纳😂
我目前在用酷安版本14.15_1
1.歌单⁰长按删除时间再延长一点
2.可以设置¹隐藏状态栏，或者²直接隐藏，再或者³在歌词页面隐藏状态栏。（状态栏的出现太牺牲这个歌词页面颜值了）
3.还有我觉的歌单页面那个⁴复制歌单按钮大可不必
4.因为这个歌词页面ui特别漂亮，建议在设置里保留⁵自定义字体功能
5.主页面搜索⁶🔍按钮再被激活时隐藏[放大镜]图标

**Comment by Web-Cooler** [comment]
觉得状态栏直接隐藏了的比沉浸的要好，要么可以在歌词页隐藏😂

**Comment by cy745** [comment]
现在1.5.0版本的，歌单相关的都已经重做了，自定义歌词字体的功能也有，不过这两个都还有待改进，
搜索功能独立成页了，这样是为了更统一而且方便全局搜索内容，主页面因为页面结构限制只能展示歌曲，所以就不打算在主页面里做搜索了，之后会尝试在主页面里添加一些更实用的操作逻辑，现在的主页面还是算简陋了

你说的歌词页隐藏状态栏的其实很OK，做起来也很简单，这个会加到任务进程里，
应该会加一个滑块开关吧，变成自由选择显示策略的，先定默认不隐藏、播放时隐藏、展开歌词页隐藏三种

**Comment by cy745** [comment]
@Web-Cooler

**Comment by cy745** [comment]
1.5.0重构后这些问题都不存在了
