### ISSUE TITLE
反馈一些问题

### ISSUE THREAD

**Issue by amokiel** [cy745/LMusic#11]
LMusic版本更新到了1.5.0
1.歌词界面开启简化页面顶部没有沉浸，有黑边。
（手机型号：Huawei Mate 20 系统版本：Harmony OS 3.0.0.108）
![bug](https://user-images.githubusercontent.com/70591216/223034009-2a2e21bd-ff41-4cf2-a1ff-5eb8a60d8ab5.jpg)
2.沉浸模式无法隐藏全局状态栏。（状态栏如果可以全局隐藏，体验会更好一些。）
3.歌词页面暂时无法常亮显示。（目前歌词页面很快就会跟随系统一起息屏。）
4.图标可以考虑更换为浅色系。（状态栏和桌面的图标显示都有些突兀，可以还用L这个字母，修改下样式就好。）
5.显示当前播放的横幅提示是否有这个必要。（个人愚见去掉这个功能似乎也没有什么影响，以前的版本似乎都没有加入这个功能。）
6.支持设置为系统默认音乐播放器。（目前虽然可以设置，但在文件管理打开歌曲无法正常播放。）
7.点击歌词页面无法选中那一行播放。（可以考虑增加歌词页面拖动和选中播放功能。）
8.歌词背景动态取色效果。（以后版本可以考虑提供歌词背景的动态取色效果。）
开发者辛苦了，多谢。个人很喜欢LMusic，页面美观，动画丝滑，很符合自身需求，以后完全可以成为个人的主力音乐播放器。LMusic很有潜力，以后一定会更加出色。

**Comment by cy745** [comment]
简单回复一下，看看能不能解决一点问题
1.你看看设置里是不是有隐藏挖孔的功能，单独对某一个应用设置的那种，这个情况昨天也有人反馈，我还不太清楚是不是有需要我适配的地方，但是把隐藏挖孔的功能先关掉应该就能让这个黑边消失
2.现在只做了展开歌词页以后隐藏的逻辑，接下来会做一个无操作n秒后自动隐藏的逻辑，这样应该能满足
3.展开歌词页常亮这个我先记下来
4.状态栏图标下个版本会替换，但是主图标我不知道改怎么改好，等我弄懂了自定义主图标的方法后也许可以做一个自定义主图标颜色的功能
5.那个横幅你如果不喜欢的话在设置里关闭就好，也是这个版本加上的开关（设置->其他->操作反馈弹窗）
6.其实和文件系统交互的那些都没做，之前只是先试了试文档上说的配置，不过不用担心，我也挺想要这个功能的，所以这个一些功能应该也会排在比较前面的位置的
7.这个其实我也很想做，但是本身整个的页面结构已经限制了上下滑动的逻辑，所以实际要做的话不会特别简单，可能会要先长按进入“歌词滑动模式”然后才能拖动歌词，最后还要点击一个“退出”按钮才能结束这个逻辑，现在有一个最可行的方法就是拖动进度条联动歌词滚动，这算是曲线救国的一种方法吧，只能满足“滚动歌词”这一个简单的需求。。。
8.你说的这个动态取色具体是指什么呢？是像Apple Music那样的“动态”背景吗？或者是要取色之后显示在什么地方吗？

**Comment by cy745** [comment]
> 

这个应用挺好看挺有趣的，这个效果加上去的话的确挺不错的，可是实现这种效果的算法我一点头绪都没有，我先记下来吧，等有头绪了我就能做了

**Comment by cy745** [comment]
@amokiel 我发了一个1.5.2_beta的包，你下载来试试看能不能解决顶部黑边的问题
[LMusic Beta](https://github.com/cy745/LMusic/releases/tag/Beta)

**Comment by cy745** [comment]
@amokiel  你再试试这个，刚才好像是写错了没有生效
https://github.com/cy745/LMusic/releases/download/Beta/LMusic_beta_1.5.2_40_20230307_1727+0800.apk

**Comment by cy745** [comment]
@amokiel 再试试这个，我这次是拿虚拟机测过的了，应该是没问题了的
https://github.com/cy745/LMusic/releases/download/Beta/LMusic_beta_1.5.2_40_20230307_2044+0800.apk

**Comment by cy745** [comment]
其实一开始网络歌词这些是为了方便那些不会用音乐标签的人才做出来的，但现在看来的确是无所谓的东西了，我其实还想做一个联网的“系统”，所以应该还是需要网络权限的，不瞒你说其实这整个项目其实算是我的毕业设计，但现在来看复杂度还达不到要求，所以我打算做一个配套的后端来扩展一部分功能，比如说部分用户数据的云端同步、歌单的共享功能等等，都不涉及版权内容所以不会有风险的，当然这些内容并不是强制开启呀什么的，应该会另外出一个独立的beta包过完毕业设计的答辩再看看实际效果如何决定留存，如果用户都喜欢的话就顺利转正，如果意见很多的话就作废了。

关于捐献的话，为了简洁我不太想在App里加没必要的页面，所以加页面就算了吧，我应该最多加一个跳转按钮在设置页的最下面，其实我也有打算用爱发电作为捐献渠道，但是看了看别人都是额外提供一些东西的，我没有什么能额外提供的了，源码和应用本体还有内测包是任何人都能自取的，可能我只能提供一个“代码的专人一对一讲解”的服务了，不过要是有人直接来问我我也不好拒绝回答，总之捐献这种事我觉得还是要慎重些，先多谢你的好意了
