### ISSUE TITLE
调整应用图标

### ISSUE THREAD

**Issue by amokiel** [cy745/LMusic#13]
可以考虑把图标换成白底加上黑色的L样式，或者其它冷色调的色彩也可以。目前的红底白色L过于鲜艳了，而且状态栏显示情况也很突兀。希望先换一个朴素点的图标，以后也可以换成精心设计的图标。辛苦了！

**Comment by cy745** [comment]
状态栏的图标我试着替换了，但是我这看不到状态栏上图标的效果，得等之后发个测试包来看看效果了。主图标的颜色这个我再决定一个颜色好了，我不是专业的设计师所以还是尽量简单比较好，对我来说容易做多错多可能越改越丑
