### ISSUE TITLE
增加歌词播放页面常亮功能

### ISSUE THREAD

**Issue by amokiel** [cy745/LMusic#14]
目前歌词播放页面很快就息屏了，可以加个页面常亮功能，最好再增加一个全局隐藏状态栏功能，那样听歌体验会更沉浸。多谢！

**Comment by cy745** [comment]
之前在忙没有回复，实际有在做的，就再等等吧

**Comment by cy745** [comment]
831ba8cfe49f25c9a197ad6011b7e6f65f6ef6e2 已完成，下个版本上线
