### ISSUE TITLE
增加定位当前播放歌曲

### ISSUE THREAD

**Issue by amokiel** [cy745/LMusic#16]
主要是在文件夹浏览中发现没有定位当前歌曲的方法，这样就不是很方便了。所以希望增加这个功能。多谢！

**Comment by cy745** [comment]
https://github.com/cy745/LMusic/commit/b4a98bfdfe0efc8152b8c87f2f50797bdc222d53 已完成，同样也有定位当前播放的歌曲、专辑、艺术家的功能
