### ISSUE TITLE
通知栏控制按钮不显示

### ISSUE THREAD

**Issue by BlueQuantumx** [cy745/LMusic#26]
MIUI 14.0.8 小米12Pro
![Screenshot_2023-05-04-10-58-54-578_com miui home](https://user-images.githubusercontent.com/78394824/236103501-f52863ce-6dc8-422c-a939-8b54fe4c6bb7.jpg)

**Comment by cy745** [comment]
这么奇怪啊

**Comment by BlueQuantumx** [comment]
哦对了MIUI默认不给未知来源APP通知权限，我看这个APP进去的时候也没提醒申请权限，甚至不给权限也能有音乐通知栏，不知道是不是这个问题？不过我就算手动给了通知权限也没解决这个问题

**Comment by BlueQuantumx** [comment]
以及我手机root了 用了noactive模块，不过已经试过给白名单了也不行（这个应该不影响吧

**Comment by BlueQuantumx** [comment]
MIUI 推送了 14.0.13 问题解决
