### ISSUE TITLE
请问这个图片里的状态栏歌词怎么做到的

### ISSUE THREAD

**Issue by CGBB0** [cy745/LMusic#31]
![Screenshot_2023-06-04-21-13-02-444_info.muge.appshare.jpg](https://github.com/cy745/LMusic/assets/101496448/0e4c5e4d-3c58-41a5-8d03-0de9f42c2961)

我看墨·状态栏歌词也没有适配Lmuisc啊

**Comment by cy745** [comment]
[LMusicNotifier.kt 媒体通知和状态栏歌词更新的部分](https://github.com/cy745/LMusic/blob/dev/app/src/main/java/com/lalilu/lmusic/service/LMusicNotifier.kt)
```kotlin
private fun startLoop(mediaSession: MediaSessionCompat) {
    notificationLoopJob?.cancel()
    notificationLoopJob = notificationBuilderFlow.flatMapLatest { builder ->
        val mediaId = mediaSession.getMediaId()
  
        coverRepo.fetch(mediaId).mapLatest {
            builder?.loadCoverAndPalette(mediaSession, it)?.build()
        }
    }.combine(lyricRepo.currentLyricSentence) { notification, sentence ->
        notification?.setLyricTicker(sentence)
    }.combine(settingsSp.enableStatusLyric.flow(true)) { notification, enable ->
        notification?.apply {
            if (enable == true && mediaSession.isPlaying()) return@apply
  
            clearLyricTicker()
        }
    }
  // .debounce(50)
        .onEach {
            statusBarLyric.updateLyric(it?.tickerText?.toString() ?: "")
            notificationManager.notify(NOTIFICATION_PLAYER_ID, it)
        }.launchIn(this)
}
```

[AppModule.kt StatusBarLyricExt初始化的部分](https://github.com/cy745/LMusic/blob/dev/app/src/main/java/com/lalilu/lmusic/AppModule.kt)

[SettingsScreen.kt 控制状态栏歌词的开关的部分](https://github.com/cy745/LMusic/blob/dev/app/src/main/java/com/lalilu/lmusic/compose/new_screen/SettingsScreen.kt)

```kotlin
if (RomUtils.isMeizu() || statusBarLyricExt.hasEnable() || CustomRomUtils.isFlyme) {
    SettingSwitcher(
        titleRes = R.string.preference_lyric_settings_status_bar_lyric,
        state = statusBarLyric
    )
}
```

墨·状态栏歌词可以用Hook的方法来主动适配不支持的app，但是它也有提供用于适配的api，也就是这个StatusBarLyricExt。

看完这三个文件的基本你也会适配状态栏歌词了，但是这还不算完整，有一些类原生系统也是有状态栏歌词的，但是我这里还没有适配。 @CGBB0

**Comment by CGBB0** [comment]
哈哈，我原本以为不支持状态栏歌词，以为图片中是别的用户自己适配的，所以才来问，结果您上来一堆看不懂的东西，把我看懵了。索性看着您发的东西和状态栏歌词的官方文档硬生生琢磨了半天，一直打包不成功。后来在app/build.gradle看到了有关状态栏歌词的注释，才意识到lmusic本来就支持状态栏歌词。

**Comment by CGBB0** [comment]
之前状态栏没有显示歌词是因为我用的lmusic自带的匹配歌词。在我使用音乐标签把歌词写入歌曲中后，状态栏就可以正常显示歌词了。

**Comment by cy745** [comment]
> 哈哈，我原本以为不支持状态栏歌词，以为图片中是别的用户自己适配的，所以才来问，结果您上来一堆看不懂的东西，把我看懵了。索性看着您发的东西和状态栏歌词的官方文档硬生生琢磨了半天，一直打包不成功。后来在app/build.gradle看到了有关状态栏歌词的注释，才意识到lmusic本来就支持状态栏歌词。

https://gitee.com/lalilu/lmusic/issues/I6WR79

打包不成功应该是缺了签名，你看看这个网页里面应该能解决
