### ISSUE TITLE
如何导入已有的 .lrc 歌词文件？

### ISSUE THREAD

**Issue by qiran233** [cy745/LMusic#36]
如何导入已有的 .lrc 歌词文件？

**Comment by cy745** [comment]
@qiran233 修改成和音乐文件同名然后放在音乐文件同目录下就好，像这样：

![S31217-13263853_com meizu filemanager](https://github.com/cy745/LMusic/assets/35896157/60d96cc1-8cd7-4db6-ae6d-b533aeb81098)
